{% set name = "DockerMake" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bd76865ae4f392833ebc39aa39870334c094bdbea67fd5627a7f7ec71e064c67

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - docker-make = dockermake.__main__:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - docker-py >=3.2
    - future
    - python >=3.6
    - pyyaml
    - termcolor

test:
  imports:
    - dockermake
  commands:
    - docker-make --help

about:
  home: https://github.com/avirshup/dockermake
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Build manager for docker images
  description: |
    A command line tool to build and manage stacks of docker images. 
    You can mix and match different sets of build instructions as a 
    dependency graph to create maintainable and extensible stacks 
    of docker images.
  doc_url: https://github.com/avirshup/dockermake
  dev_url: https://github.com/avirshup/dockermake

extra:
  recipe-maintainers:
    - CurtLH
