appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ergH2yMgMD52JraI/KIoFdl/MeIndFEDvQANhFBDk9nXTtZ1WBRIw/XhsYf14xLMM0GZWnLwvIA9JJqT7aatJWsVrLnbwnRTHxYVpJs6/bgQYWM2NhvMr5u2H4a4y16hrrdMMsk6YyELJZkOE11EXXUR8Yg7uNTNKUP6kpoF+mnGKL77+u/ZqZn8Ms5XtQvnRghTlSAb4GZnCKUN1B8Oi9c/XUw2oQlLHeCDaCCNJynv+OuYYmRRrfbUschBsFNLMF4Uwg3sTU+ncFxLHbMQoQ3gqGxZjvzHZYArntNCj1iR7zz0+p8GD0eifUOMmPpAz/7g3HEPPuRPBHIIrU2DZguY3KtIl8F9jEQ6+vCd7mq+BhHqif9WDtpTnGKlkaveb+ch2SMu5qNtTSbnOBcKRiHYB/ZxstucIqUc5lFdV4cJmlDPCY0GvVoxc1kgsaUi1i2Ft2obAADJYTCn01j9hmkAJwol70a5te6BzLC8gqUPZ/fluLr1glJh14yRVO1c44qLTW4LvSQH8O+MhdoDEScqlTGhQyPJqMfPVAn35CN241uJGK+7y+EVdvei+l1MIeOuY4BKTqDPUXGcoxrbjiJOYMO6dcIct5nWqmE724NV6jbTIEZK/T775yVH48Ne+Lo/SlVBqxilsmPaaoCPuo6P1VGJORmzUzZhJ8CeKEE=}
