travis:
  secure:
    BINSTAR_TOKEN: n7NEBlBFWjxxtmlK+YReEmW5vG2CddWCwIVlvqheDDZmu2oaoihKHPPGof4rrKpI9bUuaxlD6LAH4ulzbfdUAwJcbKbcBsNj5PFN5rSjmPczsb4w8g46Q4iHIgntD4gNLkcnc7EL1wrfOx/OHRNt34j6zh07dx5N7AtvcaQkKFh3Ic8xK/fPYIj10hU2x88jRAEPKBotimL03xDM/TW4BOIJmueHQyemd+E/jarOTGN1gf7bbFSnwC9bAgQj0jkfb+yVy+/NaZl4zeoOAhG84SRucuQ4lKUWuYRgjqUuwIZlDjEwJvSkwUYEmV9h8GmpNCQWvcEheNXguQ65UB9maqhgs3C4z3lh1/bitooIDE9GNm34XCTTNpJioKI4aWWCwt7g+c6nFeOIDrsT6dpqu2gXi0DkZbnWOXMrC4e+4g7CCa56Xloxq6H73/SAKUlODDnz8eT3fphVAn7PufPaYGR+ESTRUsCndZVxQmWIZxSTtTORe/VmGv4k8gF//RA8CERMT+ZSxDGYnKTBG25tyspTVZy/M7g4LTiNSWUorV/zm3LMB3fur4z5PbCGGx0hoNSPzzK7F6THGCikuhXN7rywX0ia3tePzDa9qELbe28S1YnOxGxDpupQTlVtLDkqjApQlFvYVrk1Mw1j5Ml2CGNPlzD+IawZZdHQQ6qzmXk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
